schemaVersion: 2.0

timeout: 30

machine:
  env:
    RUNTIME_JDK_VERSION: 11

pipelines:
  - branchName: master
    build:
      template: buildozer:v4:prb

  - branchName: master
    build:
      template: buildozer:v4:publish
    package:
      release: true
      libraries:
      - publish:
        - repo: m2:health