schemaVersion: 2.0

timeout: 30

pipelines:
  - branchName: master
    build:
      template: buildozer:v4:prb

  - branchName: master
    build:
      template: buildozer:v4:publish
    package:
      libraries:
      - publish:
        - repo: m2:health